import React, { useCallback, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { COLORS } from '../constants';
import { aiApi, AiPrivacyCoach } from '../services/api';

export function AiPrivacyCoachScreen() {
  const [result, setResult] = useState<AiPrivacyCoach | null>(null);
  const [loading, setLoading] = useState(false);

  // Simple on-device signals we can gather without new permissions.
  const run = async () => {
    setLoading(true);
    try {
      const signals = {
        os: 'unknown',
        appVersion: '1.0',
        hasVaultPin: true,
        vaultUnlocked: false,
        lastBackupDays: -1,
      };
      const res = await aiApi.privacyCoach(signals);
      setResult(res);
    } catch (e: any) {
      Alert.alert('Privacy Coach', e?.message || 'The coach is unavailable right now.');
    } finally {
      setLoading(false);
    }
  };

  const riskColor =
    result?.riskLevel === 'critical' || result?.riskLevel === 'high'
      ? COLORS.danger
      : result?.riskLevel === 'medium'
      ? COLORS.warning
      : COLORS.safe;

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <View style={styles.header}>
        <Text style={styles.icon}>🧭</Text>
        <Text style={styles.title}>AI Privacy Coach</Text>
        <Text style={styles.subtitle}>Contextual tips to tighten your privacy.</Text>
      </View>

      <TouchableOpacity style={styles.primaryButton} disabled={loading} onPress={run}>
        <Text style={styles.primaryButtonText}>{loading ? 'Analyzing…' : 'Get advice'}</Text>
      </TouchableOpacity>

      {result && (
        <View style={[styles.card, { borderColor: riskColor }]}>
          <Text style={styles.riskLabel}>Risk level</Text>
          <Text style={[styles.riskValue, { color: riskColor }]}>{result.riskLevel.toUpperCase()}</Text>
          {result.tips.map((t, i) => (
            <View key={i} style={styles.tipRow}>
              <Text style={styles.tipBullet}>•</Text>
              <Text style={styles.tipText}>{t}</Text>
            </View>
          ))}
        </View>
      )}

      <View style={styles.honest}>
        <Text style={styles.honestText}>
          Tips are generated by an AI proxy. They are suggestions, not guarantees — always verify settings in your device's own controls.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.primary },
  content: { padding: 16, paddingBottom: 40 },
  header: { alignItems: 'center', marginBottom: 16 },
  icon: { fontSize: 40, marginBottom: 6 },
  title: { fontSize: 20, fontWeight: 'bold', color: COLORS.text },
  subtitle: { fontSize: 13, color: COLORS.textSecondary, marginTop: 4, textAlign: 'center' },
  primaryButton: { backgroundColor: COLORS.safe, borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 8 },
  primaryButtonText: { fontSize: 16, fontWeight: '700', color: COLORS.primary },
  card: { backgroundColor: COLORS.card, borderRadius: 12, padding: 16, marginTop: 16, borderWidth: 1 },
  riskLabel: { fontSize: 12, color: COLORS.textSecondary },
  riskValue: { fontSize: 18, fontWeight: 'bold', marginTop: 2, marginBottom: 12 },
  tipRow: { flexDirection: 'row', marginBottom: 8 },
  tipBullet: { color: COLORS.safe, marginRight: 8, fontSize: 14 },
  tipText: { flex: 1, color: COLORS.text, fontSize: 14, lineHeight: 20 },
  honest: { backgroundColor: COLORS.warning + '12', borderRadius: 12, padding: 14, marginTop: 16, borderWidth: 1, borderColor: COLORS.warning + '40' },
  honestText: { fontSize: 12, color: COLORS.textSecondary, lineHeight: 18 },
});
